### ISSUE TITLE
大佬，那个替换的代码在哪个文件夹下运行？ 

### ISSUE THREAD

**Issue by ldr123456** [AzurLaneTools/uncensor#1]

**Comment by ldr123456** [comment]
大佬，那个替换的代码在哪个文件夹下运行？

**Comment by AutumnSun1996** [comment]
命令的目的是替换掉gametip文件, 从release下载gametip之后, 在电脑端gametip所在的文件夹下运行就行
也可以不使用adb, 而是手机上下载之后使用手机上的文件管理器进行替换
