### ISSUE TITLE
目前为止最简单易用的舰名还原

### ISSUE THREAD

**Issue by MuchiBai** [AzurLaneTools/uncensor#2]
使用mt管理器直接将作者的gametip文件替换安装目录”/sdcard/Android/data/com.bilibili.azurlane/files/AssetBundles/sharecfgdata/“中的gametip文件即可生效。不需要重新安装，也不用整magisk，对各种模拟器都有效，好用得一匹。作者一定要坚持更新啊！

**Comment by MuchiBai** [comment]
> 

另外，作者能否透露一下这个文件是如何制作的，想学习一下然后自己动手制作捏

**Comment by AutumnSun1996** [comment]
多谢你的支持。
更新已经通过Github-Actions自动化了，不太需要担心。
这个文件的制作会涉及对游戏内部代码逻辑的修改，不准备对外传播，不好意思。
